wonder:
  zk:
    address: 47.102.204.172:2181
  netty:
    server:
      host: 127.0.0.1
      port: 8000
  tcc:
    type: branch


server:
  port: 9092


#spring:
#  rabbitmq:
#    host: 47.102.204.172
#    port: 5672
#    username: guest
#    password: guest
